name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: "Publish to pub.dev"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1.7.2
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version
      - name: Publish to pub.dev
        run: flutter pub publish -f
