name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: "Publish to pub.dev"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
      - uses: subosito/flutter-action@0ca7a949e71ae44c8e688a51c5e7e93b2c87e295 # v2.22.0
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version
      - name: Publish to pub.dev
        run: flutter pub publish -f
